team/urls.py
from django.urls import path

from team import views

urlpatterns = [
    path('add/', views.add_team, name='add-team'),
]

users/urls.py
from django.urls import path

from users import views


urlpatterns = [
    path('', views.dashboard),
    path('profile/create/', views.create_regular_user, name='create-regular-user'),
    path('profile/first-login/', views.first_login, name='first-login'),
    path('profile/register/', views.register, name='register-manager'),
]

voetbalpoule/urls.py
from django.contrib.auth import views
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('competition/', include('competition.urls')),
    path('match/', include('match.urls')),
    path('team/', include('team.urls')),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    pwd_changed = models.BooleanField(
        default=False, verbose_name=_('Changed initial password'))


class Competitor(models.Model):
    user = models.OneToOneField('User', on_delete=models.CASCADE, verbose_name=_('user'))
    competition = models.ForeignKey('competition.Competition', on_delete=models.CASCADE,
                                    default=None, null=True, blank=True,
                                    verbose_name=_('competition'))
    manager = models.ForeignKey('User', limit_choices_to={'is_staff': True}, related_name='manager',
                                on_delete=models.CASCADE, verbose_name=_('manager'))
    score = models.PositiveSmallIntegerField(default=0, verbose_name=_('score'))

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = _('competitor')
        verbose_name_plural = _('competitors')

users/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from competition.models import Competition


def check_matching_passwords(data, password_name='password',
                             verification_name='password_verification'):
        password = data.get(password_name)
        password_verification = data.get(verification_name)

        if password != password_verification:
            raise forms.ValidationError(_('Passwords don\'t match!'))


class RegisterForm(forms.Form):
    first_name = forms.CharField(max_length=32)
    last_name = forms.CharField(max_length=64)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password_verification = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        check_matching_passwords(cleaned_data)


class UserCreationForm(RegisterForm):
    competition = forms.ModelChoiceField(queryset=None)

    def __init__(self, manager, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['competition'].queryset = Competition.objects.filter(manager=manager)


class PasswordModificationForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    password_verification = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        check_matching_passwords(cleaned_data)

users/views.py
from datetime import date, timedelta

from django.contrib.auth.decorators import login_required, user_passes_test
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.utils.translation import ugettext_lazy as _

from competition.models import Competition
from match.models import Match, Prediction
from users.forms import RegisterForm, PasswordModificationForm, UserCreationForm
from users.models import User, Competitor


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            try:
                User.objects.create_user(
                    # Use email as username
                    email, email, password, is_staff=True,
                    first_name=first_name, last_name=last_name)
                return redirect('/')
            except IntegrityError:
                return render(request, 'registration/register.html', {
                    'form': form,
                    'error': _('The email address is already in use!')
                })

    form = RegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def dashboard(request):
    if request.user.is_staff:
        return render(request, 'dashboard/manager.html')
    elif request.user.pwd_changed:
        competitions = Competition.objects.filter(competitor__user=request.user).all()
        competitor = Competitor.objects.get(user=request.user)
        upcoming_date = date.today() + timedelta(days=1)
        upcoming = Match.objects.filter(competition=competitor.competition, date__gt=upcoming_date)
        predictions = Prediction.objects.filter(competitor=competitor)
        prediction_mapping = dict()
        for match in upcoming:
            if predictions.filter(match=match).exists():
                prediction_mapping[match] = predictions.get(match=match).prediction
            else:
                prediction_mapping[match] = None
        return render(request, 'dashboard/user.html', {
            'competitions': competitions,
            'competitor': competitor,
            'predictions': predictions,
            'prediction_mapping': prediction_mapping,
        })
    return redirect('/profile/first-login/')


@login_required
def first_login(request):
    if request.method == 'POST':
        form = PasswordModificationForm(request.POST)
        if form.is_valid():
            user = request.user
            user.set_password(form.cleaned_data.get('password'))
            user.pwd_changed = True
            user.save()
            return redirect('/')

    form = PasswordModificationForm()
    return render(request, 'registration/first_login.html', {'form': form})


@login_required
@user_passes_test(lambda u: u.is_staff)
def create_regular_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.user, request.POST)
        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            competition = form.cleaned_data.get('competition')

            try:
                user = User.objects.create_user(username=email, email=email, first_name=first_name,
                                                last_name=last_name, password=password)
                Competitor.objects.update_or_create(manager=request.user, user=user,
                                                    defaults={'competition': competition})
                return redirect('/')
            except IntegrityError:
                return render(request, 'registration/create_regular_user.html', {
                    'form': form,
                    'error': _('The email address is already in use!')
                })

    form = UserCreationForm(request.user)
    return render(request, 'registration/create_regular_user.html', {'form': form})

users/templates/dashboard/manager.html
{% extends 'base.html' %}
{% block title %}Manager Dashboard{% endblock %}
{% block content %}
    <a href="{% url 'add-team' %}">Add team</a>
    <a href="{% url 'add-competition' %}">Add competition</a>
    <a href="{% url 'manage-competitions' %}">Manage competitions</a>
    <a href="{% url 'create-regular-user' %}">Add user</a>

    <a href="{% url 'logout' %}">Logout</a>
{% endblock %}

users/templates/dashboard/user.html
{% extends 'base.html' %}

{% block title %}VoetbalPoule Dashboard{% endblock %}

{% block scripts %}
    <script>
        function submitForm() {
            document.forms["predict-match-form"].submit();
        }
    </script>
{% endblock %}

{% block content %}
    {% for competition in competitions %}
        <h3>{{ competition }}</h3>
        {% for competitor in competition.competitor_set.all|dictsortreversed:"score" %}
            <div><b>{{ competitor.score }}</b> - {{ competitor }}</div>
        {% endfor %}
        <hr/>
    {% endfor %}
    <div id="predictions">
        <h3>Predictions</h3>
        {% for prediction in predictions %}
            <div>{{ prediction }}</div>
        {% empty %}
            <div>There are no predictions.</div>
        {% endfor %}
    </div>
    <hr/>
    <div id="upcoming">
        <h3>Upcoming matches</h3>
        <table>
            <tr>
                <th>Team A</th>
                <th>Team B</th>
                <th>Date</th>
                <th>Prediction</th>
            </tr>
            {% for match, prediction in prediction_mapping.items %}
                <tr>
                    <td>{{ match.team_a }}</td>
                    <td>{{ match.team_b }}</td>
                    <td>{{ match.date }}</td>
                    <td>
                        <form id="predict-match-form" method="post"
                              action="{% url 'predict-match' match.pk %}">
                            {% csrf_token %}
                            <input type="text" name="prediction" onblur="submitForm()"
                                   value="{{ prediction|default_if_none:"" }}">
                        </form>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3">There are no upcoming matches.</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <hr/>
    <a href="{% url 'logout' %}">Logout</a>
{% endblock %}